### ISSUE TITLE
/list

### ISSUE THREAD

**Issue by ImFrosty420** [DDecoene/PortfolioOverview#1]
when refreshing you get a blank page. You are only able to fix this when deleting the /list at the end of the url. Great app! Usefull af! Video is attached.

https://user-images.githubusercontent.com/83605263/116911224-dbc8f300-ac46-11eb-96b8-064742eaff26.mp4

**Comment by DDecoene** [comment]
Well that's not what we want 🥴

I will look into this.

Thank you for your input!

Op ma 3 mei 2021 19:37 schreef ImFrosty420 ***@***.***>:

**Comment by ImFrosty420** [comment]
I also noticed the same bug happening when opening the webpage from your bookmarks (on chrome at least). Same blank page, no error message. It's probably related, that's why i'm adding it as a comment.

**Comment by DDecoene** [comment]
I think if I solve the original issue this should be solved too. Thank you
for your update!

Op ma 3 mei 2021 22:29 schreef ImFrosty420 ***@***.***>:

**Comment by ImFrosty420** [comment]
Yes, i think so too :)

**Comment by DDecoene** [comment]
For some reason, in index.html, what should be`<base href="./">` as in the commit, keeps pointing to `/PortfolioOverview`.

It is unclear why at this point.
