### ISSUE TITLE
Symbol caps

### ISSUE THREAD

**Issue by ImFrosty420** [DDecoene/PortfolioOverview#2]
When entering your symbol in the "symbol box" you cannot do it in caps. If you do, you will not see any results.

**Comment by DDecoene** [comment]
I will add a function behind the scenes that automatically converts to
lower case

Thank you for noticing!

Op ma 3 mei 2021 19:39 schreef ImFrosty420 ***@***.***>:

**Comment by DDecoene** [comment]
The way of entering assets will completely change. You will be able to pick a crypto and don't need to worry about entering symbols or api urls and stuff
