### ISSUE TITLE
Market links

### ISSUE THREAD

**Issue by ImFrosty420** [DDecoene/PortfolioOverview#3]
New idea proposal:

When adding a new asset, there could be a dropdown menu at the "market" box in wich u can select the market you prefer, if the market isn't listed, there should be an "other" option. Why would you make it a dropdown you ask? Well, it would be useful to be able to get straight to that market you prefer. Example: i see (on your website) that my RAMP has had an insane boost lets say 126% and i want to get straight to binance to sell it. I have to search, click and type wich takes way to long... so, just a quick little shortcut to get to your preffered site (market) :)

**Comment by DDecoene** [comment]
in the new update you are able to add a market and enter a link to that market so on the overview page, you get a direct link
